// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details struct {
		Errors *[]struct {
			Code        *string `json:"code,omitempty"`
			Message     *string `json:"message,omitempty"`
			Path        *string `json:"path,omitempty"`
			RecordIndex *int    `json:"record_index,omitempty"`
		} `json:"errors,omitempty"`
		Reason  *string `json:"reason,omitempty"`
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"details"`
	ErrorCode int    `json:"error_code"`
	Message   string `json:"message"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xV34/bNgz+VwRtDxtgxG7uBhR+C4ZiO2zFgvRatCgOAWcztjpbUin6LkGQ/32QZOdH",
	"4+Z2D8tTHJEiv48fRW5lYVprNGp2Mt9KV9TYQvh8Q2Rogc4a7dAfWDIWiRUGc4kMqnHnBvT3wpdibEcc",
	"ClOGeLyxKHPpmJSu5C6RLToH1bjNAtejBsLCULlUusT1kYPSjBWS3O2S4cj8/QULlocDIIJNjAHO6NHw",
	"TFDgUpUjxrHIgfxyYIhraG2DMr+dTm+y5AzbCeW9s1xALixsGgOleIRGlcDKaNEXNhnBQfi1U4SlzD8f",
	"QzjET/Z6PZyh9gGUXpmoqitIWZ/PA8GvHToWs45r1KwKYEOiMJrJNAJ0KSyZ9UbM5ncTj0txxD/zJzKR",
	"j0guRno1ySaZJ2wsarBK5vJm8mqSyahs6IsUrEr39q2skP2Pb51QgLtS5vI35JlVf/Vennls0BBhmmWx",
	"wTSjDpcZ15zW3DaH5h5Tcpd8w/z3+7d/CgsViifFtXj3BFWFJN7fhXK7rm2BNjKXB4PwV4L1mEdKMNlA",
	"TP88nwV88r7PsgJrGy+GMjodor+AnM82m9+JT7Me8YHPYHIWC7Xqc4ifvOfPPbkuPsTvsvH2/6aLbUDp",
	"F2IfWhKaxjxh6VvqNru5UJ8v/cs+5PiRcCVz+UN6GH1pP/fS06F3IX+JWvXpp9PrpZ+fj4UVqMYjOdHx",
	"Q7SjoB6v0sIrtxz+t34+BEFbZFKFu6Tp297l/5N1TqZFrrFzAtfWOBWpGWqBv6F25DpADzwIfWUu0VhE",
	"j3EWp3h+NXqlKhFjRp1vstvv+nW6qEFXQz9m1+zH0A+jTdDbFjM/slcqroqUjVWFS7dhdM+B611Y0UDQ",
	"IqPf3J+30gsYd24iNbRevL2/PN43TB0mF5R+SKQ1bkSPuXF8H6DMTwI/p4z3VlgK2hclkbcfP16v4h/2",
	"Ty/MwriWPYpfronivXVMCG0aN7DXvyM8fyrrjfgDVv+AWLx5dz9MAxcjOqTHQfCOGpnLmtnmadqYApra",
	"OM5fZ68zuXvY/RsAAP//BYDb3ygKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
