// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details struct {
		Errors *[]struct {
			Code        *string `json:"code,omitempty"`
			Message     *string `json:"message,omitempty"`
			Path        *string `json:"path,omitempty"`
			RecordIndex *int    `json:"record_index,omitempty"`
		} `json:"errors,omitempty"`
		Reason  *string `json:"reason,omitempty"`
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"details"`
	ErrorCode int    `json:"error_code"`
	Message   string `json:"message"`
}

// GetAuthParams defines parameters for GetAuth.
type GetAuthParams struct {
	// XAuthenticatedUser Authenticated identity asserted by a trusted reverse proxy.
	XAuthenticatedUser *string `json:"X-Authenticated-User,omitempty"`
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFbdjhM5E32Vkr/vYlfqSYckA0PfZQEt0YI2CgMCoVFUsStpQ7dtbHcmvSjvvrK7M/lrZpYL5i5xVZfP",
	"OfXj+s64Lo1WpLxj2XfmeE4lxp+vrNV2Rs5o5SgcGKsNWS8pmgV5lIU7N1D4Lv6SnsoOB65FjOdrQyxj",
	"zlupVmybsJKcw1W3zaDPOw2WuLZiLpWgzYGDVJ5WZNl2m+yO9OILcc/2B2gt1k0MdFp1hvcWOc2l6DB2",
	"RY7k5zuGtMHSFMSy0WAw7Cdn2I4o3zmzGWZgsC40ClhjIQV6qRU0wvZgavWioNJl8Pkr1fNSuhI9z296",
	"cB3AwuRlBvzZUoyGy6uLJ8PLZxejxbPLi+eD5dXFlXi+FM8vnz4VQvRY0kHJ0rdKWhIs+3zIZg81uUv9",
	"zZkAIYBUS90UiONWmgA9cKJvFTkP48rnpLzk6LUFrpW3ugBUAozVmxrG00nEJX0jxTicsIStybom0pNe",
	"v9cP2mlDCo1kGRv2nvT6rCmSWGIpVk25rMifY1ErqTaAeyTkwOcEvJCkfASz1PYWrWjOlbYlFvIfEiBF",
	"+MTXIBV8vDggQ+LivSPbg9kYkHMy3oH0oFVRw21OKgZymn8lD4bIQswZOUAFtDGF5NIXdRBkKVeVPbiq",
	"523lPIl5EEiSg8kUtIUXk5ezHvyBTvIoKkgHSnuoHAlAt0e6qGE2DpqGHoyVNBEsY3+SD59F1SyW5Ck0",
	"7edTrY4o7oOic2TDyaIGhBYhWAppoiaV4UoZQuSEgixLmMIy5LRLN5a0o6erz25CVTZzKGZ30O83c0R5",
	"UjG/njY+NQVKtR9iXZG2yQ/KEotC35IIZTXqD0+iown5idKlX9pBsb/j/5aWLGP/S/eTNG3HaHo8Q++5",
	"X5CS7fWDweNdPz2fMkuURUCyTZiryhJtzTL2obET2BavVLF/5rv/ZZgR4Zs0JyyOeu+s7F43Hr8uqVOr",
	"OTkXOgILuaYTMm/kmlSwG6sXLeqSvJXc3Qf7bevyS3GX5HOqXBgJ2skmIWH6+BMOB6476JGHJRT1fSxm",
	"0eHXcXhHdi05Be0bLNuEXT5mRx0ACOOwBXEkXtBAnlaApdAJ90sXPbq1OwbxIo5xaGI2fT3sj37oVyme",
	"o1rt5k//MedP7P/Opm9ts3H7KjU6uVtcheXlHqHetS7/rcpyXxY/WWSvr9++AYMrglvpc2jvg/eTEwZ7",
	"A4RPjgikFns1Nlc/QGSGn4Ljg3QO87QL/ROs/jakxtMJfBq3UPdEdiZniMtlewf8Fjx/b1h5bSR36ff4",
	"9E7R59u4eB8/7fE5jpv03WN8588OVz9vK3rgRTbadYg21c5fRyjTo8APNcw07jZhg9jVasJGHz8+XiN8",
	"uHsB4+7YLNtxeD0mivfGeUtYps0yHNqysnQ++zc1/IXLrwizV++ud4+yayI6sutdwitbhAXMe5OlaaE5",
	"Frl2PrvqX/XZ9mb7bwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
