// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details struct {
		Errors *[]struct {
			Code        *string `json:"code,omitempty"`
			Message     *string `json:"message,omitempty"`
			Path        *string `json:"path,omitempty"`
			RecordIndex *int    `json:"record_index,omitempty"`
		} `json:"errors,omitempty"`
		Reason  *string `json:"reason,omitempty"`
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"details"`
	ErrorCode int    `json:"error_code"`
	Message   string `json:"message"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWXW/bNhT9KwS3hw1QLMV2mkRvxlaswVrMcNKiRRAYN+KVxVYiWZJybAT+7wNJyZ+q",
	"0z7ET5Z5Dy/PuTyX5DPNZKWkQGENTZ+pyQqswH++1VrqCRolhUE3oLRUqC1HH2ZogZfmMIBunv/iFqsO",
	"QCaZz2eXCmlKjdVczOgqohUaA7PumAJbdAY0ZlKzKRcMF1sALizOUNPVKmqH5ONXzCzdDIDWsAw5wEjR",
	"md5qyHDKWUewK7MXP20V4gIqVSJNh/3+IIkOuO1IXoPpBFKiYFlKYGQOJWdguRQkFLZHxlo+lliZlNx/",
	"w+W04qYCmxUPPXLnyJKbv1OSXeZsOMivzs4HF5dnw8fLi7Prfn51dsWuc3Z98eYNY6xHow5JGr/XXCOj",
	"6f22mg3VaL31DwcFcAm4yGUwiMk0V46604TfazSWjGpboLA8Ays1yaSwWpYEBCNKy8WSjMY3nhe3oRQj",
	"N0IjOkdtQqbzXtJLXO2kQgGK05QOeue9hAaTeIvFUAe7zNC6H2c/X8QbRlP6D1pHgzqxwd5+Uj9Jgj2F",
	"ReGnWVzYWJXAxaY3uoywin6gFspSPiFzbIfJYC87KFW6OnAp4q+N/zZr/K4xpyn9Ld40aNx0Z7zbmkfW",
	"Zyh4s3y/f7rlx4fmzYGXjskqoqauKtBLmtJPIY5EN3y5IG7npu3/ylnPzYkLhPL4lr4LiNfb1LGWGRpD",
	"uCFQ8jnuiXnP5yhcXGn52LCu0GqemWO0PzSQV+VdoS2wNgQXShoeNkTqCuyehi1oS93r0AhseUzFxANe",
	"T8Mt6jnP0NU+cFlF9OKUHbVFQEjbktgpnqsB33eARtcJx0vnEd212yXxlxQ5n5GQM/T1IBn+EFeLrAAx",
	"a8+f5JTnj+//zqZvYpORO/1zHm6d2DzBzN2JRwp120B+zmWFrcpfNNm7uw/viYIZkiduC9KsRz7e7CnY",
	"BIibsiMg1tBbQlj6BSET+OKAL8rZ3qc29S+o+k+hGI1vyJdRQ3UjpA0ZhRnPmzXIHw75Z1BlpeKZiZ/9",
	"5TwGW6z8ew40VGjRPfPun6nr5vBAi6iAytFZ4+n2i8LqGqMj3B8iqqTpKNpYGnvnqYx3Er/UMA7NkRG9",
	"9mpEh58/n64RPq1vQP8kCW84f3idksVHZaxGqOLwxnJtWWs8PPsXS/Iv5N+ATN7e3rWXsgkZDep5u+G1",
	"LmlKC2tVGselzKAspLHpVXKV0NXD6v8AAAD//6WgzYxVDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
